// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_71FP-v4M-3qw4CYLcmhVPQzENySwHE',
    appId: '1:722967042979:web:01e72513ab83573cfa1816',
    messagingSenderId: '722967042979',
    projectId: 'authentication-f5ac3',
    authDomain: 'authentication-f5ac3.firebaseapp.com',
    storageBucket: 'authentication-f5ac3.appspot.com',
    measurementId: 'G-M17KS1MYT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjornlXR9sWz1hErFcoy6O7DP86YebMLk',
    appId: '1:722967042979:android:0760066999ab177bfa1816',
    messagingSenderId: '722967042979',
    projectId: 'authentication-f5ac3',
    storageBucket: 'authentication-f5ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmCmx4Vj2Wh_p8Cwc15L7VrmftfMHPGIk',
    appId: '1:722967042979:ios:5f8f3dc6b76c2c64fa1816',
    messagingSenderId: '722967042979',
    projectId: 'authentication-f5ac3',
    storageBucket: 'authentication-f5ac3.appspot.com',
    androidClientId: '722967042979-pujoc4ulpurqobfrdgb6sv1ihcrhv4t8.apps.googleusercontent.com',
    iosClientId: '722967042979-gmmrfkpieqkp3nfo0vko216ok3e1j7lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmCmx4Vj2Wh_p8Cwc15L7VrmftfMHPGIk',
    appId: '1:722967042979:ios:5f8f3dc6b76c2c64fa1816',
    messagingSenderId: '722967042979',
    projectId: 'authentication-f5ac3',
    storageBucket: 'authentication-f5ac3.appspot.com',
    androidClientId: '722967042979-pujoc4ulpurqobfrdgb6sv1ihcrhv4t8.apps.googleusercontent.com',
    iosClientId: '722967042979-gmmrfkpieqkp3nfo0vko216ok3e1j7lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT_71FP-v4M-3qw4CYLcmhVPQzENySwHE',
    appId: '1:722967042979:web:3d5c9e1086990487fa1816',
    messagingSenderId: '722967042979',
    projectId: 'authentication-f5ac3',
    authDomain: 'authentication-f5ac3.firebaseapp.com',
    storageBucket: 'authentication-f5ac3.appspot.com',
    measurementId: 'G-CMTC9TR1VQ',
  );

}